services:
  office2pdf:
    build:
      context: .
      target: office2pdf-dev
      platforms:
        #- linux/amd64
        - linux/arm64
    image: office2pdf-dev
    volumes:
      - ./:/app/
    ports:
      - "3000"
    tty: true
