swagger: '2.0'
info:
  title: Office2Pdf v1 EU API
  description: Converts .docx files to .pdf files.
  version: 1.0.0
schemes:
  - https
produces:
  - application/pdf
x-google-backend:
  address: https://office2pdf-v1-eu-938182106590.europe-west1.run.app
  protocol: h2
  path_translation: APPEND_PATH_TO_ADDRESS
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /convert:
    post:
      operationId: convertDocxToPdf
      summary: "Convert .docx to .pdf"
      description: "Uploads a .docx file and returns a converted .pdf file."
      consumes:
        - multipart/form-data
      produces:
        - application/pdf
      parameters:
        - in: formData
          name: file
          description: "The .docx file to be converted."
          required: true
          type: string
      responses:
        200:
          description: "Successfully converted the file."
          schema:
            type: string
          headers:
            Content-Disposition:
              type: string
              description: 'Indicates the filename for the converted file, e.g., "example.pdf".'
        400:
          description: "Bad request. The input file is invalid or missing."
        500:
          description: "Internal server error. Conversion failed."
      security:
        - api_key: [ ]